---
- name: Set lighthouse based on configured lighthouse-host
  ansible.builtin.set_fact:
    nebula_lighthouse_hostname: "{{ inventory_hostname }}"
  delegate_to: "{{ item }}"
  loop: "{{ groups['all'] }}"
  run_once: true
  when: nebula_lighthouse is true

- name: Place nebula config
  ansible.builtin.template:
    src: config.yml.j2
    dest: /etc/nebula/config.yml
    mode: '0644'
  notify:
    - restart nebula
