---
- name: Place nebula config
  ansible.builtin.template:
    src: config.yml.j2
    dest: /etc/nebula/config.yml
    mode: '0644'

# gather hostname van host welke lighthouse is 

# get extern ip van lighthouse
# get intern nebula ip van lighthouse