---
- name: Generate certificate location
  ansible.builtin.file:
    path: "{{ nebula_certificate_location }}"
    state: directory
    mode: '0644'
  when: nebula_ca_host

- name: Generate additional hosts
  ansible.builtin.command: |
    /usr/local/bin/nebula-cert sign -name "{{ ansible_hostname | default(nebula_hostname) }}" -ip {{ nebula_host_ip }}/24
  args:
    chdir: "{{ nebula_certificate_location }}"
  register: gen_add_host
  failed_when: "'existing cert' not in gen_add_host.stderr"
  changed_when: false
  delegate_to: "{{ nebula_ca_hostname }}"
