---
- name: "Download Nebula {{ nebula_version }}"
  ansible.builtin.get_url:
    url: "https://github.com/slackhq/nebula/releases/download/v{{ nebula_version }}/nebula-linux-{{ nebula_architecture }}.tar.gz"
    dest: "{{ nebula_install_location }}/nebula-installer.tar.gz"
    mode: 0755

- name: "Extract Nebula {{ nebula_version }}"
  ansible.builtin.unarchive:
    src: "{{ nebula_install_location }}/nebula-installer.tar.gz"
    dest: "{{ nebula_install_location }}"
    remote_src: true

- name: Cleanup installer
  ansible.builtin.file:
    path: "{{ nebula_install_location }}/nebula-installer.tar.gz"
    state: absent

- name: Create nebula dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "/var/log/nebula"
    - "/etc/nebula"
    - "{{ nebula_certificate_location }}"
