---
- name: "Download Nebula {{ nebula_version }}"
  ansible.builtin.get_url:
    url: "https://github.com/slackhq/nebula/releases/download/v{{ nebula_version }}/nebula-linux-{{ nebula_architecture }}.tar.gz"
    dest: /usr/local/bin/nebula-installer.tar.gz

- name: "Extract Nebula {{ nebula_version }}"
  ansible.builtin.unarchive:
    src: "/usr/local/bin/nebula-installer.tar.gz"
    dest: /usr/local/bin/
    remote_src: true

- name: Cleanup installer
  ansible.builtin.file:
    path: /usr/local/bin/nebula-linux-{{ nebula_architecture }}.tar.gz
    state: absent 