---
- name: Pre-flight checks
  ansible.builtin.include_tasks: pre_flight.yml

- name: Download and install Nebula
  ansible.builtin.include_tasks: install.yml
  when:
    (nebula_bin_version.stdout is version (nebula_version, '>')) or
    (nebula_bin_availability.stat.exists is false)

- name: Generate CA-certificate
  ansible.builtin.include_tasks: generate_ca.yml
  when: nebula_ca_host

# - name: Generate host-certificate
#   ansible.builtin.include_tasks: generate_hosts.yml

# - name: Install Nebula systemctl-service
#   ansible.builtin.include_tasks: service.yml

# - name: Configure Nebula
#   ansible.builtin.include_tasks: configure.yml
