---
- name: Pre-flight checks
  ansible.builtin.include_tasks: pre_flight.yml

# - name: Download and install Nebula
#   ansible.builtin.include_tasks: install.yml
#   when: nebula_installed_version.stdout is version (nebula_version, '>')

# - name: Install Nebula service
#   ansible.builtin.include_tasks: service.yml

- name: Generate certificates
  ansible.builtin.include_tasks: generate.yml

# - name: Configure Nebula
#   ansible.builtin.include_tasks: configure.yml