---
- name: Pre-flight checks
  ansible.builtin.include_tasks: pre_flight.yml

- name: Download and install Nebula
  ansible.builtin.include_tasks: install.yml
  when: (nebula_version is version(nebula_current_version, '>')) or
        (nebula_bin_availability.stat.exists is false)

- name: Generate CA certificate(s)
  ansible.builtin.include_tasks: ca.yml

- name: Generate certificate(s)
  ansible.builtin.include_tasks: certificates.yml

- name: Configure Additional subnets
  ansible.builtin.include_tasks: unsafe_routes.yml
  when: nebula_unsafe_routes is true

- name: Install Nebula systemctl-service
  ansible.builtin.include_tasks: service.yml

- name: Configure Nebula
  ansible.builtin.include_tasks: configure.yml
