---
- name: Check for Nebula-binary
  ansible.builtin.stat:
    path: /usr/local/bin/nebula
  register: nebula_bin_availability

- name: Install prerequisites
  ansible.builtin.package:
    name: tar
    state: present

- name: Gather version
  block:
    - name: Gather Nebula-binary version
      ansible.builtin.shell: "/usr/local/bin/nebula -version | awk '/Version:/ {print $2}'"
      changed_when: false
      register: nebula_bin_version

    - name: Setting host facts using complex arguments
      ansible.builtin.set_fact:
        nebula_current_version: "{{ nebula_bin_version.stdout }}"
  when: nebula_bin_availability.stat.exists is true

- name: Add machine with nebula_lighthouse defined to lighthouse group
  ansible.builtin.add_host:
    name: "{{ ansible_hostname }}"
    groups: lighthouse
  when: nebula_lighthouse is true
