---
- name: Check for Nebula-binary
  ansible.builtin.stat:
    path: /usr/local/bin/nebula
  register: nebula_bin_availability

- name: Check for Nebula CA
  ansible.builtin.stat:
    path: "{{ nebula_certificate_location }}/ca.crt"
  register: nebula_ca_availability

- name: Gather version
  ansible.builtin.shell: "/usr/local/bin/nebula -version | awk '/Version:/ {print $2}'"
  changed_when: false
  register: nebula_bin_version

- name: Gather CA-host
  ansible.builtin.set_fact:
    nebula_ca_hostname: "{{ inventory_hostname }}"
  run_once: true
  when: nebula_ca_host
