---
- name: Place systemctl config on server
  ansible.builtin.template:
    src: nebula.service.j2
    dest: /etc/systemd/system/nebula.service
    mode: '0644'

- name: Enable Nebula service
  ansible.builtin.service:
    name: nebula
    enabled: true
